// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0YL55H22_61HEvEGHxkmE_U6ICuYS0Y',
    appId: '1:119871886959:web:7879076073065fd6c95f9a',
    messagingSenderId: '119871886959',
    projectId: 'dynamic-link-bd',
    authDomain: 'dynamic-link-bd.firebaseapp.com',
    storageBucket: 'dynamic-link-bd.appspot.com',
    measurementId: 'G-E3GSHBTG6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeX5cqzcZZgM_Zs6O417iTrIOK8w6mQeg',
    appId: '1:119871886959:android:9a364a22be044bd4c95f9a',
    messagingSenderId: '119871886959',
    projectId: 'dynamic-link-bd',
    storageBucket: 'dynamic-link-bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJiYB7J-9t5wAybIi1XR1m8r7rUdWc67w',
    appId: '1:119871886959:ios:2dff869da5094f32c95f9a',
    messagingSenderId: '119871886959',
    projectId: 'dynamic-link-bd',
    storageBucket: 'dynamic-link-bd.appspot.com',
    iosBundleId: 'com.example.flutterDynamicLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJiYB7J-9t5wAybIi1XR1m8r7rUdWc67w',
    appId: '1:119871886959:ios:08115843c8abf738c95f9a',
    messagingSenderId: '119871886959',
    projectId: 'dynamic-link-bd',
    storageBucket: 'dynamic-link-bd.appspot.com',
    iosBundleId: 'com.example.flutterDynamicLink.RunnerTests',
  );
}
